version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1.0
  # https://circleci.com/developer/orbs/orb/circleci/aws-ecr
  aws-ecr: circleci/aws-ecr@6.15.0
jobs:
  test:
    executor:
      name: node/default
      tag: 14.15.1
    steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run:
        command: npm test
        name: Run Mocha tests
    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output
    - store_test_results:
        path: /tmp/test-results


workflows:
  build_and_deploy-Prod:                                             
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_PROD_URL
          aws-access-key-id: AWS_PROD_ACCESS_KEY
          aws-secret-access-key: AWS_PROD_SECRET_KEY
          create-repo: true
          dockerfile: buil/Dockerfile.prod
          no-output-timeout: 20m
          path: 
#          region: AWS_REGION_PROD
          repo: backend
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
